import pandas as pd
datos= pd.read_csv('movies3.csv', encoding='latin-1')
df= pd.DataFrame(datos)
print(df)
print("Máxima duración de películas: ")
print(df['duration'].max())
minutos= df['duration'].max()
print("Las horas de la peli son: ", minutos // 60)
print("La película más larga es: ")
idx = df['duration'].idxmax()
print(df.loc[idx, 'movie_title'])
print("Comparación de likes entre géneros: ")
df1= df.groupby('genres')['movie_facebook_likes'].sum().reset_index()
print(df1)
print("El género más gustado en Facebook: ")
likes= df.groupby('genres')['movie_facebook_likes'].sum().reset_index()
print(likes.loc[likes['movie_facebook_likes'].idxmax(), 'genres'])
print(" con: " , likes['movie_facebook_likes'].max(), " likes")
print("¿Cuál es el promedio de presupuesto por directo? ")
df2= df.groupby('director_name')['budget'].mean().reset_index()
print(df2)
print("¿Cuál es el género que gasta más dinero?: ")
dinero= df.groupby('genres')['budget'].mean().reset_index()
print(dinero)
print("cual es el actor principal que trae mas ganancia")
actor= df.groupby('actor_1_name')['gross'].sum().reset_index()
actor.to_csv('actor_ganancias.csv', index=False)
print(actor.loc[actor['gross'].idxmax(), 'actor_1_name'])